name: Build ArtisanKRNL (r8s)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            build-essential bc bison flex libssl-dev libelf-dev \
            ccache clang lld llvm-dev \
            git zip unzip curl python3 python3-pip \
            libarchive-tools cpio lz4 zstd \
            p7zip-full jq xxd patchelf \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            python3-setuptools python3-cryptography \
            brotli libpcre2-dev protobuf-compiler

      - name: Setup Toolchain (Clang 18)
        run: |
          mkdir -p toolchain/clang_18
          curl -LSs "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz" -o clang.tar.gz
          tar -xzf clang.tar.gz -C toolchain/clang_18
          rm clang.tar.gz

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc
          sudo apt clean

      - name: Build Kernel (r8s)
        run: |
          chmod +x build.sh
          ./build.sh -m r8s -k y -r n

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: ArtisanKRNL-r8s-Release
          path: build/out/r8s/*.zip
